[34m[1mwandb[39m[22m: Downloading large artifact protein-sequences:v0, 83.71MB. 3 files...
[34m[1mwandb[39m[22m:   3 of 3 files downloaded.
Done. 0:0:0.1
Traceback (most recent call last):
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/cycformer/checkpoint-76146/resolve/main/config.json
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1166, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1507, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-643df3cc-256bbc896f8fea95172b91a4)
Repository Not Found for url: https://huggingface.co/cycformer/checkpoint-76146/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/wynne/Desktop/jacob/cycformer_git/cycformer/train.py", line 298, in <module>
    main()
  File "/Users/wynne/Desktop/jacob/cycformer_git/cycformer/train.py", line 96, in main
    model = EsmForSequenceClassification.from_pretrained(MODEL,
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2269, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/transformers/configuration_utils.py", line 546, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/Users/wynne/opt/anaconda3/envs/cycformer/lib/python3.10/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: cycformer/checkpoint-76146 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
loading file:  artifacts/protein-sequences:v0/train_seqs
done.
loading file:  artifacts/protein-sequences:v0/val_seqs
done.
File type:  fasta
done.